// 10 Official IPL Teams Configuration for IPL Auction Arena
const INITIAL_BUDGET = 1200000000; // ₹120 Crore (120,00,00,000)
const MAX_SQUAD_SIZE = 15;
const MAX_OVERSEAS = 6;

const DEFAULT_TEAMS = [
  {
    id: "csk",
    name: "Chennai Super Kings",
    shortName: "CSK",
    code: "CSK",
    color: "#F9CD05",
    secondaryColor: "#005BAA",
    accentColor: "#F58220",
    badgeBg: "from-yellow-500 to-amber-600",
    borderGlow: "rgba(249, 205, 5, 0.5)",
    textColor: "#000000",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2b/Chennai_Super_Kings_Logo.svg/200px-Chennai_Super_Kings_Logo.svg.png",
    fallbackIcon: "🦁",
    themeClass: "csk-theme",
    players: []
  },
  {
    id: "mi",
    name: "Mumbai Indians",
    shortName: "MI",
    code: "MI",
    color: "#004BA0",
    secondaryColor: "#D1AB3E",
    accentColor: "#0077B6",
    badgeBg: "from-blue-600 to-indigo-800",
    borderGlow: "rgba(0, 75, 160, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Mumbai_Indians_Logo.svg/200px-Mumbai_Indians_Logo.svg.png",
    fallbackIcon: "🌀",
    themeClass: "mi-theme",
    players: []
  },
  {
    id: "rcb",
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    code: "RCB",
    color: "#EC1C24",
    secondaryColor: "#000000",
    accentColor: "#D4AF37",
    badgeBg: "from-red-600 to-red-950",
    borderGlow: "rgba(236, 28, 36, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Royal_Challengers_Bangalore_2020.svg/200px-Royal_Challengers_Bangalore_2020.svg.png",
    fallbackIcon: "👑",
    themeClass: "rcb-theme",
    players: []
  },
  {
    id: "kkr",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    code: "KKR",
    color: "#3A225D",
    secondaryColor: "#D1AB3E",
    accentColor: "#9333EA",
    badgeBg: "from-purple-800 to-indigo-950",
    borderGlow: "rgba(147, 51, 234, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Kolkata_Knight_Riders_Logo.svg/200px-Kolkata_Knight_Riders_Logo.svg.png",
    fallbackIcon: "⚔️",
    themeClass: "kkr-theme",
    players: []
  },
  {
    id: "rr",
    name: "Rajasthan Royals",
    shortName: "RR",
    code: "RR",
    color: "#EA1A85",
    secondaryColor: "#004B8C",
    accentColor: "#EC4899",
    badgeBg: "from-pink-600 to-rose-900",
    borderGlow: "rgba(234, 26, 133, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/60/Rajasthan_Royals_Logo.svg/200px-Rajasthan_Royals_Logo.svg.png",
    fallbackIcon: "🛡️",
    themeClass: "rr-theme",
    players: []
  },
  {
    id: "srh",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    code: "SRH",
    color: "#F26522",
    secondaryColor: "#000000",
    accentColor: "#F97316",
    badgeBg: "from-orange-600 to-red-800",
    borderGlow: "rgba(242, 101, 34, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/81/Sunrisers_Hyderabad.svg/200px-Sunrisers_Hyderabad.svg.png",
    fallbackIcon: "🦅",
    themeClass: "srh-theme",
    players: []
  },
  {
    id: "dc",
    name: "Delhi Capitals",
    shortName: "DC",
    code: "DC",
    color: "#004C97",
    secondaryColor: "#DC0032",
    accentColor: "#3B82F6",
    badgeBg: "from-blue-700 to-cyan-900",
    borderGlow: "rgba(0, 76, 151, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Delhi_Capitals_Logo.svg/200px-Delhi_Capitals_Logo.svg.png",
    fallbackIcon: "🐅",
    themeClass: "dc-theme",
    players: []
  },
  {
    id: "pbks",
    name: "Punjab Kings",
    shortName: "PBKS",
    code: "PBKS",
    color: "#DD1F2D",
    secondaryColor: "#C9A050",
    accentColor: "#E11D48",
    badgeBg: "from-red-600 to-amber-800",
    borderGlow: "rgba(221, 31, 45, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Punjab_Kings_logo.svg/200px-Punjab_Kings_logo.svg.png",
    fallbackIcon: "🦁",
    themeClass: "pbks-theme",
    players: []
  },
  {
    id: "gt",
    name: "Gujarat Titans",
    shortName: "GT",
    code: "GT",
    color: "#1B2133",
    secondaryColor: "#BC9B5D",
    accentColor: "#14B8A6",
    badgeBg: "from-slate-800 to-teal-950",
    borderGlow: "rgba(20, 184, 166, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Gujarat_Titans_Logo.svg/200px-Gujarat_Titans_Logo.svg.png",
    fallbackIcon: "⚡",
    themeClass: "gt-theme",
    players: []
  },
  {
    id: "lsg",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    code: "LSG",
    color: "#0057E7",
    secondaryColor: "#E05A47",
    accentColor: "#0EA5E9",
    badgeBg: "from-sky-700 to-blue-950",
    borderGlow: "rgba(14, 165, 233, 0.6)",
    textColor: "#FFFFFF",
    totalBudget: INITIAL_BUDGET,
    remainingBudget: INITIAL_BUDGET,
    maxPlayers: MAX_SQUAD_SIZE,
    maxOverseas: MAX_OVERSEAS,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Lucknow_Super_Giants_IPL_Logo.svg/200px-Lucknow_Super_Giants_IPL_Logo.svg.png",
    fallbackIcon: "🦅",
    themeClass: "lsg-theme",
    players: []
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_TEAMS, INITIAL_BUDGET, MAX_SQUAD_SIZE, MAX_OVERSEAS };
}
