const fs = require('fs');

const rawPlayers = [
  // ==================== BATTERS (50) ====================
  { name: "Virat Kohli", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 98, matches: 252, runs: 8004, sr: 131.9, hs: "113*", spec: "IPL All-Time Run Machine & Master Anchor" },
  { name: "Rohit Sharma", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 257, runs: 6628, sr: 131.1, hs: "109*", spec: "Hitman • 5-Time Champion Skipper" },
  { name: "Shubman Gill", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 103, runs: 3216, sr: 135.7, hs: "129", spec: "Orange Cap Winner & Modern Maestro" },
  { name: "Suryakumar Yadav", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 150, runs: 3594, sr: 145.3, hs: "103*", spec: "World No. 1 T20 360° Innovator" },
  { name: "Yashasvi Jaiswal", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 94, matches: 52, runs: 1607, sr: 150.8, hs: "124", spec: "Fastest 50 Record Holder (13 Balls)" },
  { name: "Ruturaj Gaikwad", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 93, matches: 66, runs: 2380, sr: 136.9, hs: "108*", spec: "CSK Captain & Classical Strokeplayer" },
  { name: "Rinku Singh", role: "Batter", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 45, runs: 893, sr: 143.3, hs: "67*", spec: "Ice-Cool 5-Sixes Finisher" },
  { name: "Travis Head", role: "Batter", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 25, runs: 772, sr: 184.2, hs: "102", spec: "Nuclear Powerplay Destroyer" },
  { name: "Faf du Plessis", role: "Batter", category: "Overseas", country: "South Africa", basePrice: 20000000, tier: "Platinum", rating: 91, matches: 145, runs: 4571, sr: 136.4, hs: "96", spec: "Dynamic Veteran Leader & Elite Athlete" },
  { name: "David Warner", role: "Batter", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Platinum", rating: 93, matches: 184, runs: 6565, sr: 139.8, hs: "126", spec: "3-Time Orange Cap Legend" },
  { name: "Sai Sudharsan", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 89, matches: 28, runs: 1034, sr: 139.2, hs: "103", spec: "Technically Gifted Lefty Anchor" },
  { name: "Harry Brook", role: "Batter", category: "Overseas", country: "England", basePrice: 20000000, tier: "Platinum", rating: 90, matches: 19, runs: 390, sr: 130.5, hs: "100*", spec: "England Power Prodigy" },
  { name: "Devon Conway", role: "Batter", category: "Overseas", country: "New Zealand", basePrice: 15000000, tier: "Platinum", rating: 90, matches: 23, runs: 924, sr: 141.3, hs: "92*", spec: "Kiwi Precision Opening Batter" },
  { name: "Rajat Patidar", role: "Batter", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 90, matches: 27, runs: 799, sr: 158.9, hs: "112*", spec: "Middle-Overs Spin Crusher" },
  { name: "Tilak Varma", role: "Batter", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 38, runs: 1156, sr: 146.3, hs: "84*", spec: "Fearless Lefty Middle-Order Pillar" },
  { name: "Shreyas Iyer", role: "Batter", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 94, matches: 115, runs: 3127, sr: 127.5, hs: "96", spec: "IPL Winning Captain & Spin Dominator" },
  { name: "Prithvi Shaw", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 86, matches: 79, runs: 1892, sr: 147.5, hs: "99", spec: "Hyper-Aggressive Opening Blaster" },
  { name: "Nitish Rana", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 87, matches: 107, runs: 2636, sr: 135.3, hs: "87", spec: "Versatile Spin Attacker & Leader" },
  { name: "Rahul Tripathi", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 86, matches: 95, runs: 2236, sr: 139.5, hs: "93", spec: "High-Intent No. 3 Accelerant" },
  { name: "Kane Williamson", role: "Batter", category: "Overseas", country: "New Zealand", basePrice: 15000000, tier: "Gold", rating: 88, matches: 79, runs: 2128, sr: 126.1, hs: "89", spec: "Captain Cool & Master Tactician" },
  { name: "Steve Smith", role: "Batter", category: "Overseas", country: "Australia", basePrice: 15000000, tier: "Gold", rating: 87, matches: 103, runs: 2485, sr: 128.1, hs: "101", spec: "Classy Modern Test & T20 Maestro" },
  { name: "Ajinkya Rahane", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 86, matches: 185, runs: 4642, sr: 123.4, hs: "105*", spec: "Reinvented T20 Power Hitter" },
  { name: "Mayank Agarwal", role: "Batter", category: "Indian", country: "India", basePrice: 10000000, tier: "Silver", rating: 85, matches: 127, runs: 2661, sr: 133.5, hs: "106", spec: "Experienced Top Order Aggressor" },
  { name: "Abhinav Manohar", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 84, matches: 21, runs: 261, sr: 138.8, hs: "42", spec: "Hard-Hitting Lower Order Muscle" },
  { name: "Sameer Rizvi", role: "Batter", category: "Indian", country: "India", basePrice: 7500000, tier: "Emerging", rating: 83, matches: 8, runs: 51, sr: 118.6, hs: "21", spec: "UP Powerhitter Prodigy" },
  { name: "Nehal Wadhera", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 85, matches: 20, runs: 350, sr: 140.0, hs: "64", spec: "Lefty Finish Specialist" },
  { name: "Ayush Badoni", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 85, matches: 42, runs: 634, sr: 132.1, hs: "55*", spec: "Baby AB • Innovative Finisher" },
  { name: "Ashutosh Sharma", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Emerging", rating: 87, matches: 11, runs: 189, sr: 167.3, hs: "61", spec: "Death Overs Ramp Specialist" },
  { name: "Shashank Singh", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Gold", rating: 88, matches: 24, runs: 423, sr: 161.4, hs: "68*", spec: "Clutch Match Winner" },
  { name: "Angkrish Raghuvanshi", role: "Batter", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 84, matches: 10, runs: 163, sr: 155.2, hs: "54", spec: "U-19 World Cup Prodigy" },
  { name: "Jake Fraser-McGurk", role: "Batter", category: "Overseas", country: "Australia", basePrice: 15000000, tier: "Platinum", rating: 93, matches: 9, runs: 330, sr: 234.0, hs: "84", spec: "World Record Strike Rate Sensation" },
  { name: "Tristan Stubbs", role: "Batter", category: "Overseas", country: "South Africa", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 18, runs: 405, sr: 182.4, hs: "71*", spec: "Death Overs 360° Demolisher" },
  { name: "Tim David", role: "Batter", category: "Overseas", country: "Australia", basePrice: 15000000, tier: "Gold", rating: 89, matches: 38, runs: 659, sr: 170.3, hs: "46", spec: "Colossal Long-Handle Striker" },
  { name: "Glenn Phillips", role: "Batter", category: "Overseas", country: "New Zealand", basePrice: 10000000, tier: "Gold", rating: 87, matches: 8, runs: 65, sr: 154.8, hs: "25", spec: "Superhuman Fielder & Finisher" },
  { name: "Rovman Powell", role: "Batter", category: "Overseas", country: "West Indies", basePrice: 15000000, tier: "Gold", rating: 88, matches: 26, runs: 359, sr: 146.5, hs: "67*", spec: "Windies T20 Captain & Muscle Hitter" },
  { name: "Shimron Hetmyer", role: "Batter", category: "Overseas", country: "West Indies", basePrice: 15000000, tier: "Platinum", rating: 90, matches: 72, runs: 1231, sr: 152.9, hs: "75", spec: "Clutch Caribbean Finisher" },
  { name: "David Miller", role: "Batter", category: "Overseas", country: "South Africa", basePrice: 20000000, tier: "Platinum", rating: 92, matches: 130, runs: 2924, sr: 139.2, hs: "101*", spec: "Killer Miller - Legendary Chase Master" },
  { name: "Will Jacks", role: "Batter", category: "Overseas", country: "England", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 8, runs: 230, sr: 175.6, hs: "100*", spec: "41-ball Century Blaster" },
  { name: "Rilee Rossouw", role: "Batter", category: "Overseas", country: "South Africa", basePrice: 10000000, tier: "Gold", rating: 86, matches: 22, runs: 473, sr: 157.1, hs: "82*", spec: "Explosive Left-Handed Top-Order" },
  { name: "Manish Pandey", role: "Batter", category: "Indian", country: "India", basePrice: 7500000, tier: "Silver", rating: 83, matches: 171, runs: 3850, sr: 121.1, hs: "114*", spec: "First Indian IPL Centurion" },
  { name: "Karun Nair", role: "Batter", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 82, matches: 76, runs: 1496, sr: 127.8, hs: "83*", spec: "Domestic Triple-Centurion" },
  { name: "Priyam Garg", role: "Batter", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 80, matches: 21, runs: 251, sr: 115.1, hs: "51*", spec: "Former India U19 Skipper" },
  { name: "Yash Dhull", role: "Batter", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 80, matches: 4, runs: 16, sr: 69.6, hs: "8", spec: "U-19 World Cup Winning Captain" },
  { name: "Swastik Chikara", role: "Batter", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 79, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "UP T20 League Six-Machine" },
  { name: "Avanish Rao Aravelly", role: "Batter", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 78, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Hard Hitting Youth Star" },
  { name: "Dewald Brevis", role: "Batter", category: "Overseas", country: "South Africa", basePrice: 7500000, tier: "Gold", rating: 86, matches: 10, runs: 230, sr: 142.0, hs: "49", spec: "Baby AB • Monster Boundary Hitter" },
  { name: "Finn Allen", role: "Batter", category: "Overseas", country: "New Zealand", basePrice: 10000000, tier: "Gold", rating: 87, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Kiwi Powerplay Fireworks" },
  { name: "Charith Asalanka", role: "Batter", category: "Overseas", country: "Sri Lanka", basePrice: 7500000, tier: "Silver", rating: 84, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Sri Lanka Captain & Anchor" },
  { name: "Ibrahim Zadran", role: "Batter", category: "Overseas", country: "Afghanistan", basePrice: 7500000, tier: "Gold", rating: 86, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Afghan World Cup Record Anchor" },
  { name: "Pathum Nissanka", role: "Batter", category: "Overseas", country: "Sri Lanka", basePrice: 7500000, tier: "Gold", rating: 86, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "ODI Double Centurion" },

  // ==================== WICKET KEEPERS (35) ====================
  { name: "Rishabh Pant", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 111, runs: 3284, sr: 148.9, hs: "128*", spec: "Generational Maverick Match Winner" },
  { name: "Sanju Samson", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 167, runs: 4419, sr: 138.9, hs: "119", spec: "RR Captain & Pure Strokeplay Artist" },
  { name: "KL Rahul", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 132, runs: 4683, sr: 134.6, hs: "132*", spec: "Prolific High-Average Run Machine" },
  { name: "MS Dhoni", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 99, matches: 264, runs: 5243, sr: 137.5, hs: "84*", spec: "Thala • 5-Time Champion & Greatest Finisher" },
  { name: "Heinrich Klaasen", role: "Wicket Keeper", category: "Overseas", country: "South Africa", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 35, runs: 993, sr: 168.3, hs: "104", spec: "Most Dangerous Spin Destroyer on Planet" },
  { name: "Nicholas Pooran", role: "Wicket Keeper", category: "Overseas", country: "West Indies", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 76, runs: 1769, sr: 162.3, hs: "77", spec: "Maximum Sixes Caribbean Titan" },
  { name: "Jos Buttler", role: "Wicket Keeper", category: "Overseas", country: "England", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 107, runs: 3582, sr: 147.5, hs: "124", spec: "World Cup Winning Captain & 7 IPL 100s" },
  { name: "Ishan Kishan", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 20000000, tier: "Platinum", rating: 92, matches: 105, runs: 2644, sr: 135.9, hs: "99", spec: "Pocket Dynamo Double Centurion" },
  { name: "Quinton de Kock", role: "Wicket Keeper", category: "Overseas", country: "South Africa", basePrice: 20000000, tier: "Platinum", rating: 93, matches: 107, runs: 3157, sr: 134.2, hs: "140*", spec: "World Class Southpaw Opener" },
  { name: "Phil Salt", role: "Wicket Keeper", category: "Overseas", country: "England", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 21, runs: 653, sr: 175.5, hs: "89*", spec: "Ultra-Aggressive Opening Blaster" },
  { name: "Dhruv Jurel", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 90, matches: 28, runs: 347, sr: 151.5, hs: "56*", spec: "Composed Test Star & T20 Finisher" },
  { name: "Jitesh Sharma", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 40, runs: 730, sr: 151.1, hs: "49*", spec: "First-Ball Strike Finisher" },
  { name: "Rahmanullah Gurbaz", role: "Wicket Keeper", category: "Overseas", country: "Afghanistan", basePrice: 10000000, tier: "Gold", rating: 88, matches: 13, runs: 289, sr: 133.8, hs: "57", spec: "Afghan Powerplay Explosive Opener" },
  { name: "Anuj Rawat", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 24, runs: 318, sr: 119.1, hs: "66", spec: "Lefty Keeper & Middle Aggressor" },
  { name: "Prabhsimran Singh", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 34, runs: 756, sr: 150.3, hs: "103", spec: "Flamboyant Punjab Century Maker" },
  { name: "Shai Hope", role: "Wicket Keeper", category: "Overseas", country: "West Indies", basePrice: 7500000, tier: "Silver", rating: 85, matches: 9, runs: 183, sr: 150.0, hs: "41", spec: "Classy Anchor with T20 Gears" },
  { name: "Ryan Rickelton", role: "Wicket Keeper", category: "Overseas", country: "South Africa", basePrice: 7500000, tier: "Gold", rating: 86, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "SA20 Top Run Scorer" },
  { name: "Josh Inglis", role: "Wicket Keeper", category: "Overseas", country: "Australia", basePrice: 15000000, tier: "Gold", rating: 89, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Aussie T20 360° Keeper Batter" },
  { name: "Kumar Kushagra", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 5000000, tier: "Emerging", rating: 81, matches: 4, runs: 3, sr: 60.0, hs: "3", spec: "Jharkhand Big Hitting Talent" },
  { name: "Robin Minz", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 5000000, tier: "Emerging", rating: 82, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Left-Handed Power Striker" },
  { name: "KS Bharat", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 81, matches: 10, runs: 199, sr: 122.1, hs: "78*", spec: "Dependable Gloveman & Top Order" },
  { name: "Vishnu Vinod", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 80, matches: 6, runs: 56, sr: 140.0, hs: "30", spec: "Kerala Heavy Hitter" },
  { name: "Sheldon Jackson", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 80, matches: 9, runs: 61, sr: 107.0, hs: "16", spec: "Saurashtra Domestic Giant" },
  { name: "Donovan Ferreira", role: "Wicket Keeper", category: "Overseas", country: "South Africa", basePrice: 5000000, tier: "Silver", rating: 83, matches: 2, runs: 8, sr: 100.0, hs: "7", spec: "Hard-Hitting All-Round Keeper" },
  { name: "Kusal Mendis", role: "Wicket Keeper", category: "Overseas", country: "Sri Lanka", basePrice: 7500000, tier: "Silver", rating: 85, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Sri Lankan Explosive Top Order" },
  { name: "Tom Banton", role: "Wicket Keeper", category: "Overseas", country: "England", basePrice: 7500000, tier: "Silver", rating: 84, matches: 2, runs: 18, sr: 90.0, hs: "10", spec: "Dynamic English Scoop Specialist" },
  { name: "Matthew Wade", role: "Wicket Keeper", category: "Overseas", country: "Australia", basePrice: 10000000, tier: "Gold", rating: 86, matches: 15, runs: 179, sr: 115.5, hs: "35*", spec: "World Cup Winning Clutch Finisher" },
  { name: "Sam Billings", role: "Wicket Keeper", category: "Overseas", country: "England", basePrice: 10000000, tier: "Gold", rating: 85, matches: 30, runs: 503, sr: 129.6, hs: "56", spec: "Inventive English Middle-Order" },
  { name: "Harvik Desai", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 79, matches: 1, runs: 0, sr: 0.0, hs: "0", spec: "Saurashtra Opening Keeper" },
  { name: "Luvnith Sisodia", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 78, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Karnataka Left-Handed Striker" },
  { name: "Urvil Patel", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 80, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Domestic 28-ball T20 Centurion" },
  { name: "Ricky Bhui", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 80, matches: 4, runs: 23, sr: 76.7, hs: "17", spec: "Ranji Trophy Top Scorer" },
  { name: "Baba Indrajith", role: "Wicket Keeper", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 79, matches: 3, runs: 21, sr: 70.0, hs: "15", spec: "Tamil Nadu Solid Middle Order" },
  { name: "Johnson Charles", role: "Wicket Keeper", category: "Overseas", country: "West Indies", basePrice: 7500000, tier: "Silver", rating: 83, matches: 0, runs: 0, sr: 0.0, hs: "-", spec: "Two-Time T20 World Champion" },
  { name: "Tim Seifert", role: "Wicket Keeper", category: "Overseas", country: "New Zealand", basePrice: 7500000, tier: "Silver", rating: 84, matches: 3, runs: 26, sr: 118.2, hs: "21", spec: "Kiwi Power Striker" },

  // ==================== ALL-ROUNDERS (55) ====================
  { name: "Hardik Pandya", role: "All-Rounder", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 137, runs: 2525, wickets: 64, sr: 145.9, econ: 8.9, hs: "91", bb: "3/17", spec: "India's Premier Fast-Bowling All-Rounder" },
  { name: "Ravindra Jadeja", role: "All-Rounder", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 240, runs: 2959, wickets: 160, sr: 129.5, econ: 7.6, hs: "62*", bb: "5/16", spec: "Sir Jadeja • 3D Match Winning Maestro" },
  { name: "Andre Russell", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 127, runs: 2484, wickets: 115, sr: 174.9, econ: 9.3, hs: "88*", bb: "5/15", spec: "Dre Russ - Most Feared Striker in Cricket" },
  { name: "Sunil Narine", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 20000000, tier: "Marquee", rating: 98, matches: 177, runs: 1534, wickets: 180, sr: 165.8, econ: 6.7, hs: "109", bb: "5/19", spec: "MVP Century Opener & Mystery Legend" },
  { name: "Glenn Maxwell", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 134, runs: 2771, wickets: 37, sr: 156.7, econ: 8.3, hs: "95", bb: "2/15", spec: "Big Show • Switch-Hit Reverse Genius" },
  { name: "Axar Patel", role: "All-Rounder", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 94, matches: 150, runs: 1653, wickets: 123, sr: 130.8, econ: 7.2, hs: "66", bb: "4/21", spec: "World Cup Final Hero & Spin Wall" },
  { name: "Marcus Stoinis", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Platinum", rating: 94, matches: 96, runs: 1866, wickets: 43, sr: 142.1, econ: 9.5, hs: "124*", bb: "4/15", spec: "Hulk • Century-Making Match Finisher" },
  { name: "Sam Curran", role: "All-Rounder", category: "Overseas", country: "England", basePrice: 20000000, tier: "Platinum", rating: 93, matches: 60, runs: 883, wickets: 58, sr: 137.8, econ: 9.4, hs: "63", bb: "4/11", spec: "T20 World Cup POTT & Lefty Swing Ace" },
  { name: "Liam Livingstone", role: "All-Rounder", category: "Overseas", country: "England", basePrice: 20000000, tier: "Platinum", rating: 92, matches: 39, runs: 939, wickets: 11, sr: 162.5, econ: 8.8, hs: "70", bb: "3/27", spec: "Monster 117m Six Hitter & Dual Spin" },
  { name: "Cameron Green", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Platinum", rating: 93, matches: 29, runs: 707, wickets: 16, sr: 153.7, econ: 9.1, hs: "100*", bb: "2/12", spec: "6ft 6in Pace All-Rounder & Centurion" },
  { name: "Shivam Dube", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 93, matches: 65, runs: 1502, wickets: 5, sr: 159.2, econ: 9.6, hs: "95*", bb: "2/15", spec: "Long-Lever Spin Demolisher" },
  { name: "Washington Sundar", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 89, matches: 60, runs: 378, wickets: 37, sr: 116.3, econ: 7.4, hs: "40", bb: "3/16", spec: "Powerplay Off-Spin Restrictor" },
  { name: "Nitish Kumar Reddy", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 15, runs: 303, wickets: 3, sr: 142.9, econ: 9.1, hs: "76*", bb: "2/17", spec: "IPL Emerging Player & Fast-Bowling Sensation" },
  { name: "Mitchell Marsh", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Platinum", rating: 92, matches: 42, runs: 666, wickets: 37, sr: 125.2, econ: 8.5, hs: "89", bb: "4/25", spec: "Aussie T20 Captain & Heavy Ball Hitter" },
  { name: "Rachin Ravindra", role: "All-Rounder", category: "Overseas", country: "New Zealand", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 10, runs: 222, sr: 160.9, hs: "61", spec: "Kiwi World Cup Golden Prodigy" },
  { name: "Moeen Ali", role: "All-Rounder", category: "Overseas", country: "England", basePrice: 15000000, tier: "Gold", rating: 89, matches: 67, runs: 1162, wickets: 35, sr: 143.0, econ: 7.1, hs: "93", bb: "3/7", spec: "Classy Lefty Striker & Off-Spin Lock" },
  { name: "Shahbaz Ahmed", role: "All-Rounder", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 87, matches: 55, runs: 535, wickets: 20, sr: 128.9, econ: 8.9, hs: "59*", bb: "3/7", spec: "Impact All-Rounder & Arm Baller" },
  { name: "Rahul Tewatia", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 93, runs: 1013, wickets: 32, sr: 145.3, econ: 7.9, hs: "53", bb: "3/18", spec: "Ice-Cold Miracle Chase Specialist" },
  { name: "Krunal Pandya", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 88, matches: 127, runs: 1514, wickets: 76, sr: 133.3, econ: 7.4, hs: "86", bb: "3/14", spec: "Tactical Spinner & Aggressive Anchor" },
  { name: "Romario Shepherd", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 10000000, tier: "Gold", rating: 88, matches: 10, runs: 115, wickets: 4, sr: 221.2, hs: "39*", bb: "2/15", spec: "32-Runs in an Over Powerhitter" },
  { name: "Marco Jansen", role: "All-Rounder", category: "Overseas", country: "South Africa", basePrice: 15000000, tier: "Gold", rating: 90, matches: 21, runs: 80, wickets: 20, sr: 140.0, econ: 9.3, hs: "17*", bb: "3/25", spec: "6ft 9in Left-Arm Fire & Clean Striker" },
  { name: "Wanindu Hasaranga", role: "All-Rounder", category: "Overseas", country: "Sri Lanka", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 26, runs: 72, wickets: 35, sr: 100.0, econ: 8.1, hs: "20", bb: "5/18", spec: "T20 Top Wicket-Taking Leg Spinner" },
  { name: "Deepak Hooda", role: "All-Rounder", category: "Indian", country: "India", basePrice: 10000000, tier: "Silver", rating: 84, matches: 118, runs: 1470, wickets: 10, sr: 128.7, econ: 8.4, hs: "64", bb: "2/16", spec: "T20 Centurion & Handy Off-Break" },
  { name: "Venkatesh Iyer", role: "All-Rounder", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 51, runs: 1326, wickets: 3, sr: 137.1, hs: "104", bb: "2/29", spec: "IPL Final Match Winner & Centurion" },
  { name: "Vijay Shankar", role: "All-Rounder", category: "Indian", country: "India", basePrice: 7500000, tier: "Silver", rating: 84, matches: 72, runs: 1115, wickets: 9, sr: 131.0, econ: 8.6, hs: "63*", bb: "2/19", spec: "Experienced Middle Order Strokeplayer" },
  { name: "Ramandeep Singh", role: "All-Rounder", category: "Indian", country: "India", basePrice: 7500000, tier: "Gold", rating: 88, matches: 20, runs: 170, wickets: 6, sr: 186.8, hs: "25*", bb: "3/20", spec: "Boundary-Riding Gun & 200+ SR Finisher" },
  { name: "Lalit Yadav", role: "All-Rounder", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 82, matches: 27, runs: 305, wickets: 11, sr: 108.9, econ: 8.4, hs: "48*", bb: "2/11", spec: "Delhi Utility Spin All-Rounder" },
  { name: "Mahipal Lomror", role: "All-Rounder", category: "Indian", country: "India", basePrice: 7500000, tier: "Silver", rating: 85, matches: 40, runs: 527, wickets: 1, sr: 141.7, econ: 8.2, hs: "54*", bb: "1/7", spec: "Left-Handed Impact Striker" },
  { name: "Harpreet Brar", role: "All-Rounder", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 41, runs: 234, wickets: 25, sr: 118.8, econ: 7.6, hs: "25*", bb: "3/15", spec: "Giant Killer Left-Arm Orthodox Spinner" },
  { name: "Swapnil Singh", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 82, matches: 12, runs: 40, wickets: 7, sr: 133.3, econ: 8.8, hs: "15", bb: "2/28", spec: "Powerplay Spin Specialist" },
  { name: "Anukul Roy", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 81, matches: 11, runs: 52, wickets: 6, sr: 126.8, econ: 8.1, hs: "13", bb: "2/19", spec: "Sensational Fielder & Lefty Spinner" },
  { name: "Raj Bawa", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 80, matches: 2, runs: 11, wickets: 0, sr: 78.6, hs: "11", spec: "U19 World Cup Final 5-Wicket Star" },
  { name: "Nishant Sindhu", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 80, matches: 0, runs: 0, wickets: 0, sr: 0.0, hs: "-", spec: "India A Captain & Left-Arm Spinner" },
  { name: "Tanush Kotian", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Silver", rating: 82, matches: 1, runs: 24, wickets: 0, sr: 77.4, hs: "24", spec: "Ranji Player of the Tournament" },
  { name: "Shikhar Dhawan", role: "All-Rounder", category: "Indian", country: "India", basePrice: 20000000, tier: "Gold", rating: 89, matches: 222, runs: 6769, wickets: 4, sr: 127.1, hs: "106*", spec: "Gabbar • 2nd Highest All-Time Run Scorer" },
  { name: "Sikandar Raza", role: "All-Rounder", category: "Overseas", country: "Zimbabwe", basePrice: 10000000, tier: "Gold", rating: 88, matches: 9, runs: 182, wickets: 3, sr: 141.1, econ: 9.3, hs: "57", bb: "1/19", spec: "Zimbabwe's Global T20 Superstar" },
  { name: "Mohammad Nabi", role: "All-Rounder", category: "Overseas", country: "Afghanistan", basePrice: 10000000, tier: "Gold", rating: 87, matches: 24, runs: 215, wickets: 15, sr: 147.3, econ: 7.2, hs: "31", bb: "4/11", spec: "The President • Veteran All-Round Master" },
  { name: "Azmatullah Omarzai", role: "All-Rounder", category: "Overseas", country: "Afghanistan", basePrice: 15000000, tier: "Platinum", rating: 90, matches: 7, runs: 42, wickets: 4, sr: 102.4, econ: 8.9, hs: "17", bb: "2/27", spec: "Express Swing Bowler & Power Striker" },
  { name: "Gulbadin Naib", role: "All-Rounder", category: "Overseas", country: "Afghanistan", basePrice: 7500000, tier: "Gold", rating: 86, matches: 1, runs: 19, wickets: 0, sr: 126.7, hs: "19", spec: "Muscle Power Match Winner" },
  { name: "Dasun Shanaka", role: "All-Rounder", category: "Overseas", country: "Sri Lanka", basePrice: 7500000, tier: "Silver", rating: 84, matches: 3, runs: 26, wickets: 0, sr: 100.0, hs: "17", spec: "Sri Lanka Ex-Captain & Death Hitter" },
  { name: "Kyle Mayers", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 10000000, tier: "Gold", rating: 88, matches: 13, runs: 379, wickets: 0, sr: 144.1, econ: 8.5, hs: "73", spec: "Fierce Lefty Puller & Seam Option" },
  { name: "Odean Smith", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 7500000, tier: "Silver", rating: 83, matches: 6, runs: 51, wickets: 6, sr: 115.9, econ: 11.8, hs: "25*", bb: "4/30", spec: "145km/h Express & Long-Six Power" },
  { name: "Daniel Sams", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 7500000, tier: "Silver", rating: 84, matches: 16, runs: 44, wickets: 14, sr: 104.8, econ: 9.3, hs: "15", bb: "4/30", spec: "BBL T20 Leading Left-Arm Pacer" },
  { name: "Ashton Turner", role: "All-Rounder", category: "Overseas", country: "Australia", basePrice: 7500000, tier: "Silver", rating: 83, matches: 5, runs: 8, wickets: 0, sr: 53.3, hs: "5", spec: "Perth Scorchers Title Winning Skipper" },
  { name: "Chris Woakes", role: "All-Rounder", category: "Overseas", country: "England", basePrice: 15000000, tier: "Gold", rating: 88, matches: 21, runs: 78, wickets: 30, sr: 97.5, econ: 8.9, hs: "18", bb: "3/6", spec: "World Cup Swing King & Clean Hitter" },
  { name: "David Willey", role: "All-Rounder", category: "Overseas", country: "England", basePrice: 10000000, tier: "Gold", rating: 86, matches: 11, runs: 18, wickets: 6, sr: 62.1, econ: 7.6, hs: "18", bb: "2/16", spec: "Left-Arm Inswing & Power Striker" },
  { name: "Fabian Allen", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 5000000, tier: "Silver", rating: 82, matches: 5, runs: 14, wickets: 2, sr: 82.4, econ: 8.6, hs: "8", bb: "1/22", spec: "Superb Diving Fielder & Spinner" },
  { name: "Sherfane Rutherford", role: "All-Rounder", category: "Overseas", country: "West Indies", basePrice: 10000000, tier: "Gold", rating: 87, matches: 10, runs: 106, wickets: 1, sr: 101.9, econ: 10.3, hs: "28", bb: "1/6", spec: "CPL Title Machine & Caribbean Muscle" },
  { name: "Sanvir Singh", role: "All-Rounder", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 80, matches: 6, runs: 31, wickets: 0, sr: 172.2, hs: "18", spec: "SRH Impact Heavy Hitter" },
  { name: "Naman Dhir", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 85, matches: 7, runs: 140, wickets: 0, sr: 166.7, hs: "62*", spec: "MI Dynamic 200+ Strike Rate Finisher" },
  { name: "Suyash Sharma", role: "All-Rounder", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 84, matches: 13, runs: 0, wickets: 10, sr: 0.0, econ: 8.5, bb: "3/30", spec: "Rapid Arm Leg-Spin Prodigy" },
  { name: "Manav Suthar", role: "All-Rounder", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 80, matches: 1, runs: 0, wickets: 0, econ: 8.0, bb: "0/16", spec: "India A Left-Arm Spin Prodigy" },
  { name: "Rasikh Salam", role: "All-Rounder", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 84, matches: 11, runs: 15, wickets: 9, econ: 10.9, bb: "3/34", spec: "Kashmir Slower Ball Specialist" },
  { name: "Arshin Kulkarni", role: "All-Rounder", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 81, matches: 2, runs: 9, wickets: 0, sr: 64.3, hs: "9", spec: "Hard-Hitting Opening Seam All-Rounder" },
  { name: "Shivalik Sharma", role: "All-Rounder", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 77, matches: 0, runs: 0, wickets: 0, sr: 0.0, hs: "-", spec: "Baroda Domestic Prospect" },

  // ==================== BOWLERS (60) ====================
  { name: "Jasprit Bumrah", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 99, matches: 133, wickets: 165, econ: 7.3, bb: "5/10", spec: "World No. 1 Yorker & Death Over Maestro" },
  { name: "Pat Cummins", role: "Bowler", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Marquee", rating: 97, matches: 58, wickets: 63, econ: 8.9, bb: "4/34", spec: "World Cup & WTC Champion Captain" },
  { name: "Mitchell Starc", role: "Bowler", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Marquee", rating: 98, matches: 41, wickets: 51, econ: 8.4, bb: "4/15", spec: "150km/h Inswinging Yorker Destroyer" },
  { name: "Rashid Khan", role: "Bowler", category: "Overseas", country: "Afghanistan", basePrice: 20000000, tier: "Marquee", rating: 98, matches: 121, wickets: 149, econ: 6.8, bb: "4/24", spec: "World's Best T20 Mystery Leg-Spinner" },
  { name: "Trent Boult", role: "Bowler", category: "Overseas", country: "New Zealand", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 104, wickets: 121, econ: 8.2, bb: "4/18", spec: "First-Over Wicket Machine Inswinger" },
  { name: "Kagiso Rabada", role: "Bowler", category: "Overseas", country: "South Africa", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 80, wickets: 117, econ: 8.4, bb: "4/21", spec: "Purple Cap 150km/h Strike Weapon" },
  { name: "Mohammed Shami", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 110, wickets: 127, econ: 8.4, bb: "4/11", spec: "Purple Cap Seam Presentation King" },
  { name: "Mohammed Siraj", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 94, matches: 93, wickets: 93, econ: 8.6, bb: "4/21", spec: "Miyan Magic • Relentless Powerplay Striker" },
  { name: "Arshdeep Singh", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 65, wickets: 76, econ: 8.7, bb: "5/32", spec: "T20 World Cup Champion Death Specialist" },
  { name: "Kuldeep Yadav", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 84, wickets: 87, econ: 8.1, bb: "4/14", spec: "Unplayable Left-Arm Wrist Spin Wizard" },
  { name: "Yuzvendra Chahal", role: "Bowler", category: "Indian", country: "India", basePrice: 20000000, tier: "Marquee", rating: 96, matches: 160, wickets: 205, econ: 7.8, bb: "5/40", spec: "IPL All-Time Highest Wicket Taker (200+)" },
  { name: "Varun Chakravarthy", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 94, matches: 70, wickets: 83, econ: 7.5, bb: "5/20", spec: "Title-Winning Mystery Spinner" },
  { name: "Harshit Rana", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 21, wickets: 25, econ: 9.0, bb: "3/24", spec: "145km/h Bouncer & Back-of-Hand Slower" },
  { name: "Mayank Yadav", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 93, matches: 4, wickets: 7, econ: 6.9, bb: "3/14", spec: "156.7 km/h Raw Speed Sensation" },
  { name: "Matheesha Pathirana", role: "Bowler", category: "Overseas", country: "Sri Lanka", basePrice: 20000000, tier: "Marquee", rating: 95, matches: 20, wickets: 34, econ: 7.9, bb: "4/28", spec: "Baby Malinga - Unplayable Slingshot" },
  { name: "Anrich Nortje", role: "Bowler", category: "Overseas", country: "South Africa", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 46, wickets: 60, econ: 8.9, bb: "3/33", spec: "155km/h South African Thunderbolt" },
  { name: "Josh Hazlewood", role: "Bowler", category: "Overseas", country: "Australia", basePrice: 20000000, tier: "Platinum", rating: 94, matches: 27, wickets: 35, econ: 8.0, bb: "4/25", spec: "Laser Line & Relentless Length Machine" },
  { name: "Bhuvneshwar Kumar", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 176, wickets: 181, econ: 7.5, bb: "5/19", spec: "2-Time Purple Cap Swing King" },
  { name: "Lockie Ferguson", role: "Bowler", category: "Overseas", country: "New Zealand", basePrice: 15000000, tier: "Gold", rating: 89, matches: 45, wickets: 46, econ: 8.8, bb: "4/28", spec: "150km/h Kiwi Express Gun" },
  { name: "Avesh Khan", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 89, matches: 63, wickets: 75, econ: 8.8, bb: "4/24", spec: "Pinpoint Wide Yorker Specialist" },
  { name: "Mukesh Kumar", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 89, matches: 20, wickets: 24, econ: 10.3, bb: "3/14", spec: "Precision Death Over Yorker Machine" },
  { name: "Prasidh Krishna", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 51, wickets: 49, econ: 8.9, bb: "4/30", spec: "Tall High-Release Hit-the-Deck Pacer" },
  { name: "T Natarajan", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 61, wickets: 67, econ: 8.8, bb: "4/19", spec: "Tamil Nadu Left-Arm Yorker Master" },
  { name: "Sandeep Sharma", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 127, wickets: 137, econ: 7.9, bb: "5/18", spec: "Knuckle Ball & Dip Slower Master" },
  { name: "Khaleel Ahmed", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 90, matches: 57, wickets: 74, econ: 8.8, bb: "3/21", spec: "Left-Arm Powerplay Strike Weapon" },
  { name: "Deepak Chahar", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 89, matches: 81, wickets: 77, econ: 7.9, bb: "4/13", spec: "New-Ball Banana Swing Specialist" },
  { name: "Shardul Thakur", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Gold", rating: 88, matches: 95, wickets: 94, econ: 9.2, bb: "4/36", spec: "Lord Shardul - Golden Arm Breaker" },
  { name: "Rahul Chahar", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 87, matches: 79, wickets: 75, econ: 7.7, bb: "4/27", spec: "Aggressive Leg-Spin & Googly Merchant" },
  { name: "Ravi Bishnoi", role: "Bowler", category: "Indian", country: "India", basePrice: 15000000, tier: "Platinum", rating: 92, matches: 66, wickets: 63, econ: 7.8, bb: "3/24", spec: "World No. 1 Quick Skidding Googly Ace" },
  { name: "Noor Ahmad", role: "Bowler", category: "Overseas", country: "Afghanistan", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 23, wickets: 24, econ: 8.0, bb: "3/37", spec: "Left-Arm Mystery Chinaman Prodigy" },
  { name: "Maheesh Theekshana", role: "Bowler", category: "Overseas", country: "Sri Lanka", basePrice: 15000000, tier: "Gold", rating: 89, matches: 27, wickets: 25, econ: 7.7, bb: "4/33", spec: "Powerplay Carrom-Ball Controller" },
  { name: "Dilshan Madushanka", role: "Bowler", category: "Overseas", country: "Sri Lanka", basePrice: 10000000, tier: "Gold", rating: 88, matches: 0, wickets: 0, econ: 0.0, bb: "-", spec: "World Cup Leading Left-Arm Striker" },
  { name: "Naveen-ul-Haq", role: "Bowler", category: "Overseas", country: "Afghanistan", basePrice: 15000000, tier: "Gold", rating: 89, matches: 18, wickets: 25, econ: 9.4, bb: "4/38", spec: "Deceptive Off-Cutter & Death Bowler" },
  { name: "Spencer Johnson", role: "Bowler", category: "Overseas", country: "Australia", basePrice: 10000000, tier: "Gold", rating: 87, matches: 5, wickets: 4, econ: 9.8, bb: "2/25", spec: "150km/h Big Bash Express Lefty" },
  { name: "Gerald Coetzee", role: "Bowler", category: "Overseas", country: "South Africa", basePrice: 15000000, tier: "Platinum", rating: 91, matches: 10, wickets: 13, econ: 10.2, bb: "4/34", spec: "Fiery 150km/h Karate Kid Pacer" },
  { name: "Nuwan Thushara", role: "Bowler", category: "Overseas", country: "Sri Lanka", basePrice: 10000000, tier: "Gold", rating: 88, matches: 7, wickets: 8, econ: 9.8, bb: "3/28", spec: "Round-Arm Lasith Malinga Clone" },
  { name: "Mustafizur Rahman", role: "Bowler", category: "Overseas", country: "Bangladesh", basePrice: 15000000, tier: "Gold", rating: 90, matches: 57, wickets: 61, econ: 8.0, bb: "4/29", spec: "The Fizz • Deadly Angle & Off-Cutters" },
  { name: "Alzarri Joseph", role: "Bowler", category: "Overseas", country: "West Indies", basePrice: 10000000, tier: "Gold", rating: 87, matches: 22, wickets: 21, econ: 9.4, bb: "6/12", spec: "Best IPL Bowling Figures Record (6/12)" },
  { name: "Fazalhaq Farooqi", role: "Bowler", category: "Overseas", country: "Afghanistan", basePrice: 10000000, tier: "Gold", rating: 88, matches: 7, wickets: 6, econ: 8.6, bb: "3/11", spec: "T20 World Cup Leading Wicket Taker" },
  { name: "Nathan Ellis", role: "Bowler", category: "Overseas", country: "Australia", basePrice: 10000000, tier: "Gold", rating: 88, matches: 16, wickets: 18, econ: 8.8, bb: "4/30", spec: "World Elite T20 Death Slower Specialist" },
  { name: "Umran Malik", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 26, wickets: 29, econ: 9.4, bb: "5/25", spec: "157 km/h Jammu Express Fireball" },
  { name: "Mohit Sharma", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 89, matches: 112, wickets: 132, econ: 8.5, bb: "5/10", spec: "Purple Cap Slower Ball Virtuoso" },
  { name: "Ishant Sharma", role: "Bowler", category: "Indian", country: "India", basePrice: 7500000, tier: "Silver", rating: 85, matches: 110, wickets: 92, econ: 8.2, bb: "5/12", spec: "100+ Tests Tall Seam Veteran" },
  { name: "Umesh Yadav", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Silver", rating: 86, matches: 148, wickets: 144, econ: 8.4, bb: "4/23", spec: "Express Powerplay Swing Spearhead" },
  { name: "Piyush Chawla", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 192, wickets: 192, econ: 7.9, bb: "4/17", spec: "IPL Legend & 2nd Highest Wicket Taker" },
  { name: "Karn Sharma", role: "Bowler", category: "Indian", country: "India", basePrice: 7500000, tier: "Silver", rating: 85, matches: 84, wickets: 76, econ: 8.2, bb: "4/16", spec: "4-Time IPL Title Winning Leg Spinner" },
  { name: "Yash Dayal", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 29, wickets: 28, econ: 9.6, bb: "3/20", spec: "Left-Arm Inswing & Playoff Hero" },
  { name: "Vaibhav Arora", role: "Bowler", category: "Indian", country: "India", basePrice: 7500000, tier: "Gold", rating: 86, matches: 20, wickets: 19, econ: 9.2, bb: "3/27", spec: "Both-Ways Powerplay Swing Bowler" },
  { name: "Simarjeet Singh", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 84, matches: 10, wickets: 9, econ: 8.7, bb: "3/26", spec: "CSK Hit-the-Deck Heavy Ball Pacer" },
  { name: "Tushar Deshpande", role: "Bowler", category: "Indian", country: "India", basePrice: 10000000, tier: "Gold", rating: 88, matches: 36, wickets: 42, econ: 9.6, bb: "4/27", spec: "CSK Wicket-Taking Powerplay Pacer" },
  { name: "Chetan Sakariya", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 19, wickets: 20, econ: 8.4, bb: "3/31", spec: "Lefty Swing & Deceptive Variations" },
  { name: "Siddharth Kaul", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 82, matches: 55, wickets: 58, econ: 8.6, bb: "4/29", spec: "Experienced Knuckle-Ball Operator" },
  { name: "Kartik Tyagi", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 19, wickets: 15, econ: 10.0, bb: "4/29", spec: "150km/h U19 Sensation" },
  { name: "Kuldeep Sen", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 12, wickets: 14, econ: 9.8, bb: "4/20", spec: "Fast Bouncers & Reverse Swing" },
  { name: "Manav Oza", role: "Bowler", category: "Indian", country: "India", basePrice: 2000000, tier: "Emerging", rating: 78, matches: 0, wickets: 0, econ: 0.0, bb: "-", spec: "Young Gujarat Pacer" },
  { name: "Vidwath Kaverappa", role: "Bowler", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 82, matches: 2, wickets: 2, econ: 9.0, bb: "2/36", spec: "Karnataka Swing King" },
  { name: "Vijaykumar Vyshak", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 84, matches: 11, wickets: 13, econ: 10.1, bb: "3/20", spec: "RCB Knuckle Slower Specialist" },
  { name: "Manimaran Siddharth", role: "Bowler", category: "Indian", country: "India", basePrice: 3000000, tier: "Emerging", rating: 82, matches: 3, wickets: 1, econ: 7.2, bb: "1/21", spec: "Left-Arm Arm Ball Virtuoso" },
  { name: "Kumar Kartikeya", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 12, wickets: 10, econ: 8.7, bb: "2/22", spec: "Left-Arm Orthodox & Wrist Spinner" },
  { name: "Shreyas Gopal", role: "Bowler", category: "Indian", country: "India", basePrice: 5000000, tier: "Silver", rating: 83, matches: 52, wickets: 52, econ: 8.1, bb: "4/16", spec: "Hat-Trick Taking Leg Spinner" }
];

const roleIcons = {
  "Batter": "🏏",
  "Bowler": "⚡",
  "All-Rounder": "🔥",
  "Wicket Keeper": "🧤"
};

const countryFlags = {
  "India": "🇮🇳",
  "Australia": "🇦🇺",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "South Africa": "🇿🇦",
  "West Indies": "🌴",
  "New Zealand": "🇳🇿",
  "Afghanistan": "🇦🇫",
  "Sri Lanka": "🇱🇰",
  "Bangladesh": "🇧🇩",
  "Zimbabwe": "🇿🇼"
};

const players = rawPlayers.map((p, index) => {
  const id = index + 1;
  const flag = countryFlags[p.country] || "🌐";
  const roleIcon = roleIcons[p.role] || "🏏";
  const encodedName = encodeURIComponent(p.name);
  const avatar = "https://api.dicebear.com/7.x/bottts-neutral/svg?seed=" + encodedName + "&backgroundColor=0f172a,1e293b,1e1b4b";
  
  return {
    id: id,
    name: p.name,
    role: p.role,
    roleIcon: roleIcon,
    category: p.category,
    country: p.country,
    countryFlag: flag,
    basePrice: p.basePrice,
    currentBid: p.basePrice,
    soldPrice: null,
    soldTo: null,
    status: "UPCOMING",
    tier: p.tier,
    rating: p.rating,
    specialty: p.spec,
    image: avatar,
    stats: {
      matches: p.matches || 0,
      runs: p.runs || 0,
      wickets: p.wickets || 0,
      strikeRate: p.sr || (p.role === "Bowler" ? 0 : 130.0),
      economy: p.econ || (p.role === "Batter" ? 0 : 8.2),
      highestScore: p.hs || "-",
      bestBowling: p.bb || "-"
    }
  };
});

const out = "// 200 Curated IPL 2026 Players Pool for IPL Auction Arena\n" +
  "const PLAYERS_DATABASE = " + JSON.stringify(players, null, 2) + ";\n\n" +
  "if (typeof module !== 'undefined' && module.exports) {\n" +
  "  module.exports = { PLAYERS_DATABASE };\n" +
  "}\n";

fs.writeFileSync('C:/Users/Kadhar Basha/.gemini/antigravity/scratch/ipl-auction-arena/js/playersData.js', out);
console.log('Successfully generated js/playersData.js with ' + players.length + ' players!');
